# Generated by Django 3.0.5 on 2020-05-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('cl', models.CharField(max_length=10)),
                ('present_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='校区代码')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='校区名称')),
                ('address', models.CharField(max_length=200, verbose_name='校区地址')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='班级代码')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班级名')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('head_teacher', models.CharField(max_length=50, verbose_name='班主任')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='课程号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='课程名称')),
                ('grade_info', models.CharField(choices=[('E', '考试'), ('P', '当堂答辩')], max_length=9, verbose_name='考试方式')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='专业代码')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='专业名称')),
                ('address', models.CharField(max_length=100, verbose_name='专业地址')),
                ('charger', models.CharField(max_length=50, verbose_name='负责人')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Campus')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='school', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('identification', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, validators=[school.models.People.idvalidator], verbose_name='身份信息号')),
                ('id_type', models.CharField(choices=[('ID', '身份证'), ('PA', '护照')], default='ID', max_length=7, verbose_name='身份信息类型')),
                ('chinese_name', models.CharField(max_length=10, verbose_name='中文名')),
                ('gender_type', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=3, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='生日')),
                ('nationality', models.CharField(max_length=20, verbose_name='国籍')),
                ('family_addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址(可选)')),
                ('family_post_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='家庭邮编(可选)')),
                ('family_phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='家庭电话(可选)')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='学号')),
                ('start_date', models.DateField(verbose_name='入学年月')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Classes')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='TeacherExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('identification', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, validators=[school.models.People.idvalidator], verbose_name='身份信息号')),
                ('id_type', models.CharField(choices=[('ID', '身份证'), ('PA', '护照')], default='ID', max_length=7, verbose_name='身份信息类型')),
                ('chinese_name', models.CharField(max_length=10, verbose_name='中文名')),
                ('gender_type', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=3, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='生日')),
                ('nationality', models.CharField(max_length=20, verbose_name='国籍')),
                ('family_addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址(可选)')),
                ('family_post_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='家庭邮编(可选)')),
                ('family_phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='家庭电话(可选)')),
                ('teacher_num', models.CharField(max_length=10, unique=True, verbose_name='教职工编号')),
                ('join_date', models.DateField(verbose_name='入职年月')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('rank', models.CharField(choices=[('AP', '副教授'), ('P', '教授')], max_length=7, verbose_name='职称')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Major')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='StudyDelay',
            fields=[
                ('event_num', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='异动编号')),
                ('date', models.DateField(verbose_name='异动日期')),
                ('delay_reason', models.CharField(choices=[('D', '休学'), ('V', '支教')], max_length=5, verbose_name='降级原因')),
                ('new_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delay_to', to='school.Classes')),
                ('old_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delay_from', to='school.Classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
            options={
                'verbose_name': '降级',
                'verbose_name_plural': '降级',
            },
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=40, null=True)),
                ('fee', models.PositiveIntegerField(null=True)),
                ('cl', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight'), ('nine', 'nine'), ('ten', 'ten')], default='one', max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartedCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.DateField(verbose_name='开课年份')),
                ('semester_start', models.CharField(choices=[('春季', '春季'), ('夏季', '夏季'), ('秋季', '秋季')], max_length=7, verbose_name='开课学期')),
                ('day_start', models.CharField(choices=[('Mon', '周一'), ('Tus', '周二'), ('Wen', '周三'), ('Thu', '周四'), ('Fri', '周五')], max_length=5, verbose_name='上课日期')),
                ('when_start', models.CharField(choices=[('1', '第一节'), ('2', '第二节'), ('3', '第三节'), ('4', '第四节'), ('5', '第五节'), ('6', '第六节'), ('7', '第七节'), ('8', '第八节'), ('9', '第九节')], max_length=7, verbose_name='上课时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Teacher')),
            ],
            options={
                'verbose_name': '开课',
                'verbose_name_plural': '开课',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Major'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(through='school.StartedCourseInfo', to='school.Teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Major'),
        ),
        migrations.CreateModel(
            name='ChooseCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(null=True, verbose_name='考试成绩')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.StartedCourseInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
            options={
                'verbose_name': '选课',
                'verbose_name_plural': '选课',
            },
        ),
        migrations.CreateModel(
            name='ChangeMajor',
            fields=[
                ('event_num', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='异动编号')),
                ('date', models.DateField(verbose_name='异动日期')),
                ('change_association', models.CharField(choices=[('Y', '是'), ('N', '否'), ('NM', '不是团员')], max_length=9, verbose_name='是否转出团员关系')),
                ('new_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Change_to', to='school.Classes')),
                ('old_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Change_from', to='school.Classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
            options={
                'verbose_name': '转专业',
                'verbose_name_plural': '转专业',
            },
        ),
    ]
