# Generated by Django 3.0.5 on 2020-05-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200518_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemajor',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='school.Student', verbose_name='异动学生'),
        ),
        migrations.AlterField(
            model_name='choosecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.StartedCourseInfo', verbose_name='选课课程'),
        ),
        migrations.AlterField(
            model_name='choosecourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student', verbose_name='选课学生'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='major',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Campus', verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='startedcourseinfo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Course', verbose_name='开课课程'),
        ),
        migrations.AlterField(
            model_name='startedcourseinfo',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Teacher', verbose_name='开课教师'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Classes', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studydelay',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='school.Student', verbose_name='异动学生'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Major', verbose_name='专业'),
        ),
    ]
