# Generated by Django 3.0.5 on 2020-05-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200522_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemajor',
            name='change_association',
            field=models.CharField(choices=[('是', '是'), ('否', '否'), ('不是团员', '不是团员')], max_length=9, verbose_name='是否转出团员关系'),
        ),
        migrations.AlterField(
            model_name='changemajor',
            name='new_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Change_to', to='school.Classes', verbose_name='新班级'),
        ),
        migrations.AlterField(
            model_name='changemajor',
            name='old_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Change_from', to='school.Classes', verbose_name='原班级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade_info',
            field=models.CharField(choices=[('考试', '考试'), ('当堂答辩', '当堂答辩')], max_length=9, verbose_name='考试方式'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_type',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_type',
            field=models.CharField(choices=[('身份证', '身份证'), ('护照', '护照')], default='身份证', max_length=7, verbose_name='身份信息类型'),
        ),
        migrations.AlterField(
            model_name='studydelay',
            name='delay_reason',
            field=models.CharField(choices=[('休学', '休学'), ('支教', '支教')], max_length=5, verbose_name='降级原因'),
        ),
        migrations.AlterField(
            model_name='studydelay',
            name='new_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delay_to', to='school.Classes', verbose_name='新班级'),
        ),
        migrations.AlterField(
            model_name='studydelay',
            name='old_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delay_from', to='school.Classes', verbose_name='原班级'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender_type',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_type',
            field=models.CharField(choices=[('身份证', '身份证'), ('护照', '护照')], default='身份证', max_length=7, verbose_name='身份信息类型'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('副教授', '副教授'), ('教授', '教授')], max_length=7, verbose_name='职称'),
        ),
    ]
